In [23]:
# Import required libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score

In [2]:
# Load Data
df=pd.read_csv("Credit_Data.csv")
df.head(3)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1

In [3]:
# Remove first three column
df.drop(columns=['RowNumber', 'CustomerId', 'Surname'], inplace=True)

In [4]:
# Now check the dataset
df.head(3)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1

In [5]:
# Basic Information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  str
 2   Gender           10000 non-null  str
 3   Age              10000 non-null  int64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(2), int64(7), str(2)
memory usage: 859.5 KB

In [6]:
# Check geography column
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [7]:
# Check Gender column
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [8]:
# Value of Geograpy and Gender column are string 
# Convert string to number
df=pd.get_dummies(
    df,
    columns=['Geography', 'Gender'],
    drop_first=True,
    dtype=int)

In [9]:
# Check the dataset again
df.head(3)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,0

In [10]:
# Extract Input and output column
X=df.drop(columns=['Exited'])
y=df['Exited']

In [11]:
# Spliting the data into train and test set
X_train, X_test, y_train, y_test=train_test_split(
    X,y,
    test_size=0.2,
    random_state=42
)

In [12]:
# Scale the dataset
scale=StandardScaler()
X_train_scaled=scale.fit_transform(X_train)
X_test_scaled=scale.transform(X_test)

In [ ]:
# Create the model 
model=Sequential()

# Add model Layer
model.add(Dense(3, activation='sigmoid', input_dim=11))
model.add(Dense(1, activation='sigmoid'))

In [ ]:
# Show the model architecture
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 3)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 40 (160.00 B)

 Trainable params: 40 (160.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Configure the model
model.compile(loss='binary_crossentropy', optimizer='adam')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [18]:
# Train the model
model.fit(X_train_scaled, y_train, epochs=10)

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.8914
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.6712
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.5584
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.5060
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4812
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4682
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4601
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4538
Epoch 9/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4483
Epoch 10/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4433

In [ ]:
# First layers weight
model.layers[0].get_weights()

[array([[-0.48550525,  0.11375711,  0.26729336],
        [ 0.45171335, -2.4556196 ,  0.61587226],
        [-0.28270617,  0.06246707,  0.20913078],
        [ 0.6039964 , -0.32079083,  0.66425365],
        [ 0.21196169,  0.17038262,  0.212633  ],
        [-0.14953077, -0.14743076, -0.43258205],
        [-0.8644427 ,  0.67544967, -0.27818584],
        [ 0.36829406, -0.03429647, -0.3155368 ],
        [ 0.77100104, -0.49950156,  0.16530687],
        [-0.27697968,  0.11467492, -0.04600834],
        [-0.62916297,  0.4920762 , -0.22287045]], dtype=float32),
 array([-0.5397715 ,  1.0231853 , -0.58815604], dtype=float32)]

In [20]:
# 2nd layers weight
model.layers[1].get_weights()

[array([[ 0.3947882],
        [-1.334569 ],
        [ 0.280269 ]], dtype=float32),
 array([-0.8224564], dtype=float32)]

In [ ]:
# Perform the prediction
log_loss=model.predict(X_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [22]:
# Screen 1 and 0 using threshold
y_pred=np.where(log_loss>0.5, 1,0)

In [ ]:
# Findout the accuracy
accuracy_score(y_test, y_pred)*100

80.35

# Now improve the model

In [ ]:
# Create the model 
model=Sequential()

# Add two hidden layer
# Use relu function in hidden laye instead of sigmoid
# Use Sigmoid function in output
model.add(Dense(11, activation='relu', input_dim=11))
model.add(Dense(11, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [ ]:
# Show the model architecture
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_14 (Dense)                │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 1)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 276 (1.08 KB)

 Trainable params: 276 (1.08 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Configure the model
# Use accuracy metrics
model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy'])       # Accuracy metrics apply threshold

In [40]:
# Train the model
model.fit(X_train_scaled, y_train, epochs=50, validation_split=0.2)

Epoch 1/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6739 - loss: 0.6096 - val_accuracy: 0.7975 - val_loss: 0.4831
Epoch 2/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7967 - loss: 0.4681 - val_accuracy: 0.8106 - val_loss: 0.4354
Epoch 3/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8089 - loss: 0.4393 - val_accuracy: 0.8213 - val_loss: 0.4164
Epoch 4/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8191 - loss: 0.4247 - val_accuracy: 0.8250 - val_loss: 0.4065
Epoch 5/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8219 - loss: 0.4143 - val_accuracy: 0.8275 - val_loss: 0.3990
Epoch 6/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8288 - loss: 0.4052 - val_accuracy: 0.8256 - val_loss: 0.3924
Epoch 7/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8322 - loss: 0.3968 - val_accuracy: 0.8319 - val_loss: 0.3856
Epoch 8/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8377 - loss: 0.3875 - val_accuracy: 0.8363 - val_loss: 0.3792
Epoch 9/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8427 - loss: 0.3788 - val_accuracy: 0.8388 - val_loss: 0.3718
Epoch 10/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8450 - loss: 0.3705 - val_accuracy: 0.8369 - val_loss: 0.3656
Epoch 11/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8497 - loss: 0.3640 - val_accuracy: 0.8381 - val_loss: 0.3604
Epoch 12/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8508 - loss: 0.3585 - val_accuracy: 0.8469 - val_loss: 0.3547
Epoch 13/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8556 - loss: 0.3535 - val_accuracy: 0.8494 - val_loss: 0.3529
Epoch 14/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8572 - loss: 0.3506 - val_accuracy: 0.8512 - val_loss: 0.3495
Epoch 15/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8591 - loss: 0.3479 - val_accuracy: 0.8487 - val_loss: 0.3488
Epoch 16/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8567 - loss: 0.3463 - val_accuracy: 0.8512 - val_loss: 0.3475
Epoch 17/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8569 - loss: 0.3447 - val_accuracy: 0.8562 - val_loss: 0.3477
Epoch 18/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8602 - loss: 0.3436 - val_accuracy: 0.8544 - val_loss: 0.3459
Epoch 19/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8572 - loss: 0.3425 - val_accuracy: 0.8562 - val_loss: 0.3444
Epoch 20/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8575 - loss: 0.3419 - val_accuracy: 0.8550 - val_loss: 0.3448
Epoch 21/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8573 - loss: 0.3410 - val_accuracy: 0.8562 - val_loss: 0.3440
Epoch 22/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8602 - loss: 0.3399 - val_accuracy: 0.8506 - val_loss: 0.3445
Epoch 23/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8586 - loss: 0.3400 - val_accuracy: 0.8525 - val_loss: 0.3451
Epoch 24/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8608 - loss: 0.3390 - val_accuracy: 0.8512 - val_loss: 0.3437
Epoch 25/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8609 - loss: 0.3382 - val_accuracy: 0.8519 - val_loss: 0.3432
Epoch 26/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8606 - loss: 0.3380 - val_accuracy: 0.8519 - val_loss: 0.3431
Epoch 27/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8616 - loss: 0.3382 - val_accuracy: 0.8531 - val_loss: 0.3433
Epoch 28/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8609 - loss: 0.3366 - val_accuracy: 0.8556 - val_loss: 0.3437
Epoch 29/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8614 - loss: 0.3368 - val_accuracy: 0.8544 - val_loss: 0.3442
Epoch 30/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8625 - loss: 0.3369 - val_accuracy: 0.8525 - val_loss: 0.3420
Epoch 31/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8612 - loss: 0.3361 - val_accuracy: 0.8525 - val_loss: 0.3432
Epoch 32/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8637 - loss: 0.3355 - val_accuracy: 0.8512 - val_loss: 0.3426
Epoch 33/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8619 - loss: 0.3355 - val_accuracy: 0.8506 - val_loss: 0.3423
Epoch 34/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8612 - loss: 0.3349 - val_accuracy: 0.8544 - val_loss: 0.3427
Epoch 35/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8633 - loss: 0.3349 - val_accuracy: 0.8550 - val_loss: 0.3419
Epoch 36/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8619 - loss: 0.3345 - val_accuracy: 0.8512 - val_loss: 0.3428
Epoch 37/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8625 - loss: 0.3339 - val_accuracy: 0.8525 - val_loss: 0.3424
Epoch 38/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8639 - loss: 0.3336 - val_accuracy: 0.8519 - val_loss: 0.3437
Epoch 39/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8625 - loss: 0.3334 - val_accuracy: 0.8556 - val_loss: 0.3423
Epoch 40/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8634 - loss: 0.3337 - val_accuracy: 0.8550 - val_loss: 0.3449
Epoch 41/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8639 - loss: 0.3328 - val_accuracy: 0.8556 - val_loss: 0.3425
Epoch 42/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8637 - loss: 0.3324 - val_accuracy: 0.8544 - val_loss: 0.3435
Epoch 43/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8628 - loss: 0.3325 - val_accuracy: 0.8556 - val_loss: 0.3420
Epoch 44/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8636 - loss: 0.3316 - val_accuracy: 0.8531 - val_loss: 0.3421
Epoch 45/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8645 - loss: 0.3316 - val_accuracy: 0.8556 - val_loss: 0.3428
Epoch 46/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8641 - loss: 0.3310 - val_accuracy: 0.8550 - val_loss: 0.3414
Epoch 47/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8639 - loss: 0.3304 - val_accuracy: 0.8544 - val_loss: 0.3426
Epoch 48/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8647 - loss: 0.3306 - val_accuracy: 0.8537 - val_loss: 0.3421
Epoch 49/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8645 - loss: 0.3306 - val_accuracy: 0.8544 - val_loss: 0.3418
Epoch 50/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8633 - loss: 0.3302 - val_accuracy: 0.8550 - val_loss: 0.3453

In [ ]:
# Make prediction
y_pred=model.predict(X_test_scaled)
y_pred

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

array([[0.06451508],
       [0.01461582],
       [0.10192779],
       ...,
       [0.65406513],
       [0.06345271],
       [0.35367236]], shape=(2000, 1), dtype=float32)

In [42]:
# find the class with the highest predicted probability
y_pred = y_pred.argmax(axis=-1)

In [43]:
# Accuracy Score
accuracy_score(y_test,y_pred)

0.8035